id: diffs
learningObjectives:
  - Visual Differences
hints:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Congratulations! Now lets run the test a second time to detect visual differences."
            delay: 1500
          - text: "To do that, we will change the application (URL) under test"
            delay: 2000
          - text: "Go to src/test/AcmeBankTests.java test file and replace the driver navigation command (Line-X) 'driver.get(\"https://demo.applitools.com/index_v2.html\");'"
            delay: 1500
          - text: "Now run your test again using 'mvn test' and review the results in your [Eyes dashboard](https://eyes.applitools.com/app/test-results/)"
            delay: 1500
    - actionId: ready_message
      params:
        person: keen
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step